### ISSUE TITLE
MObjectHandle hashCode...

### ISSUE THREAD

**Issue by GuidoPollini** [mottosso/cmdx#60]
Hi:), 
first of all, thank you: cmdx is beautifully written and indeed a nice performance boost compared to PyMel and maya.cmds.

I've just a question: wrappers are stored in the Singleton._instances dictionary by using node MObjectHandle::hashCode(); however the doc explicitly says that these are just hashes and clashes are possible for nodes in the same scene... Apparently it's just a hash and not an UUID.

In case of a clash, the original wrapper will be forgotten and I didn't check yet if that's an issue (probably not:))

What do you think?

Gui

**Comment by mottosso** [comment]
Hi @GuidoPollini, thanks and happy to hear you like it. :)

> clashes are possible for nodes in the same scene

Indeed, except that leaves out the very next and most important line [from the docs](help.autodesk.com/view/MAYAUL/2020/ENU/?guid=__cpp_ref_class_m_object_handle_html#a23a0c64be863c23d2cf8214243d59bb1).

> However different MObjectHandles whose MObjects refer to the same internal Maya object will return the same hash code.

In other words, it always returns the same node in the scene, which is exactly what you want. That's how you can get the same instance of the singleton like this.

```py
instanceA = cmdx.createNode("reverse", name="myNode")
instanceB = cmdx.ls(type="reverse")[0]
assert instanceA is instanceB
```

Because they will be the same variable.

```py
instanceA._my_special_data = "Hello!"
print(instanceB._my_special_data)
# Hello!
```

**Comment by GuidoPollini** [comment]
Indeed:).
if I'm not wrong, in case of clash the Singleton._instance will lose the reference to the original wrapper and (if no cycles are involved) next garbage collection will call Node.__del__ unregistering the callbacks.
It should all be fine:)

**Comment by mottosso** [comment]
I should hope `__del__` is only called when the *last* reference is lost, rather then once there is a clash. In my code, I call `cmdx.uninstall()` on scene open to clear out any references and old commands from undo, which is when I expect `__del__` to get called.

In practice it has been working well so far. Have been using this for a few years now in all of my Maya projects, most recently/currently [ragdoll](https://github.com/mottosso/ragdoll).

Thanks for double-checking, if you come up with any optimisations or improvements, feel free to share!
