### ISSUE TITLE
unsupported type on cloned attribute

### ISSUE THREAD

**Issue by p0las** [mottosso/cmdx#80]
Am I doing it wrong? In this case I cannot copy the attribute.

```
        import cmdx
        cmds.file(new=True, force=True)
        src_node, src_node_shape = cmds.polyCube()
        dst_node, dst_node_shape = cmds.polyCube()
        attr_name = "test"
        cmds.addAttr(src_node, ln=attr_name, dt="string")

        s = cmdx.encode(src_node)

        print(s[attr_name].type())  # -> kTypedAttribute
        attr2 = s[attr_name].clone(attr_name)
        print(attr2.type())  # -> 4 ?

        d = cmdx.encode(dst_node)
        d.add_attr(attr2)
```

for some reason, the cloned attribute type is not supported when I add it to the destination node:
`TypeError: Unsupported Python type '<class 'OpenMaya.MObject'>'`

**Comment by mottosso** [comment]
Hm, unclear. Does it work with any other data type? Does this example work for you?

- https://github.com/mottosso/cmdx/pull/58

**Comment by p0las** [comment]
tested in the latest release and it works fine. sorry for the false report mate.
